#ifndef INITYPES_H
#define INITYPES_H

#define APPNAME QString("APPNAME")
#define SHORTAPPNAME QString("SHORTAPPNAME")
#define URL QString("URL")
#define ISO8559RESPONSE QString("ISO8559RESPONSE")
#define SEARCH QString("SEARCH")
#define NEWLINE QString("NEWLINE")
#define DELIMIT QString("DELIMIT")
#define OUTPUTPREFIX QString("OUTPUTPREFIX")
#define SEARCHPROMPT QString("SEARCHPROMPT")
#define ACCESSIBLESEARCHNAME QString("ACCESSIBLESEARCHNAME")
#define ACCESSIBLEOUTPUTNAME QString("ACCESSIBLEOUTPUTNAME")
#define ICON QString("ICON")

#endif // INITYPES_H
