#ifndef INITYPES_H
#define INITYPES_H

#define APPNAME QString("APPNAME")
#define SHORTAPPNAME QString("SHORTAPPNAME")
#define URL QString("URL")
#define TESTFILE QString("TESTFILE")
#define ISO8559RESPONSE QString("ISO8559RESPONSE")
#define SEARCH QString("SEARCH")
#define REPLACE1 QString("REPLACE1")
#define WITH1 QString("WITH1")
#define REPLACE2 QString("REPLACE2")
#define WITH2 QString("WITH2")
#define REPLACE3 QString("REPLACE3")
#define WITH3 QString("WITH3")
#define REPLACE4 QString("REPLACE4")
#define WITH4 QString("WITH4")
#define NEWLINE QString("NEWLINE")
#define DELIMIT QString("DELIMIT")
#define OUTPUTPREFIX QString("OUTPUTPREFIX")
#define SEARCHPROMPT QString("SEARCHPROMPT")
#define ACCESSIBLESEARCHNAME QString("ACCESSIBLESEARCHNAME")
#define ACCESSIBLEOUTPUTNAME QString("ACCESSIBLEOUTPUTNAME")
#define REMOVECOMMENTS QString("REMOVECOMMENTS")
#define ICON QString("ICON")
#define DEBUG QString("DEBUG")

#endif // INITYPES_H
